/* ════════════════════════════════════════════════════════
   AI 추천 Mock 데이터
   백엔드 API 연동 전까지 사용할 더미 데이터
   ════════════════════════════════════════════════════════ */

import { CropRecommendation, CropRecommendResponse } from './recommend.types';

export const MOCK_RECOMMENDATIONS: CropRecommendation[] = [
  {
    rank: 1,
    cropId: 1,
    cropName: '유기농 배추',
    category: '채소류',
    score: 96,
    soilFitness: 'HIGH_SUIT',
    soilFitnessPercent: 92,
    priceForecastPercent: 88,
    supplyStabilityPercent: 95,
    supplyStatus: 'BALANCED',
    expectedRevenuePerKg: 4200,
    expectedYield: 5200,
    aiReason: '해당 필지의 토양 pH와 유기물 함량이 배추 재배 최적 범위에 해당하며, 현재 양평군 내 공급량이 적정 수준을 유지하고 있어 안정적 수익이 기대됩니다.',
    growthDays: 70,
    optimalTemp: '15~20°C',
    sowingPeriod: '3월 ~ 5월',
    harvestPeriod: '파종 후 70~90일',
    difficulty: 2,
    pests: ['배추흰나비', '무름병', '진딧물'],
  },
  {
    rank: 2,
    cropId: 2,
    cropName: '청양고추',
    category: '채소류',
    score: 91,
    soilFitness: 'HIGH_SUIT',
    soilFitnessPercent: 88,
    priceForecastPercent: 90,
    supplyStabilityPercent: 85,
    supplyStatus: 'BALANCED',
    expectedRevenuePerKg: 5100,
    expectedYield: 3800,
    aiReason: '사양토 환경에서 고추의 생육이 우수하며, 양평 지역의 일교차가 크다는 특성이 고추의 매운맛 발현에 유리합니다. 시세 전망이 매우 긍정적입니다.',
    growthDays: 120,
    optimalTemp: '20~28°C',
    sowingPeriod: '2월 ~ 3월 (육묘)',
    harvestPeriod: '7월 ~ 10월',
    difficulty: 3,
    pests: ['탄저병', '역병', '진딧물'],
  },
  {
    rank: 3,
    cropId: 3,
    cropName: '방울토마토',
    category: '과일류',
    score: 87,
    soilFitness: 'SUIT',
    soilFitnessPercent: 85,
    priceForecastPercent: 82,
    supplyStabilityPercent: 90,
    supplyStatus: 'BALANCED',
    expectedRevenuePerKg: 6800,
    expectedYield: 2600,
    aiReason: '높은 시장 단가와 안정적 수요를 보이며, 현 토양 조건에서 재배 가능합니다. 시설 하우스 재배 시 연중 수확이 가능하여 수익 극대화가 가능합니다.',
    growthDays: 90,
    optimalTemp: '20~25°C',
    sowingPeriod: '2월 ~ 4월',
    harvestPeriod: '5월 ~ 11월',
    difficulty: 3,
    pests: ['잿빛곰팡이병', '흰가루병', '온실가루이'],
  },
  {
    rank: 4,
    cropId: 4,
    cropName: '감자',
    category: '곡물',
    score: 82,
    soilFitness: 'SUIT',
    soilFitnessPercent: 80,
    priceForecastPercent: 75,
    supplyStabilityPercent: 78,
    supplyStatus: 'SHORT_CAUTION',
    expectedRevenuePerKg: 1800,
    expectedYield: 8500,
    aiReason: '현재 양평군 감자 공급이 수요 대비 부족한 상태로, 수급 측면에서 유리합니다. 재배 난이도가 낮아 초보 농가에도 추천합니다.',
    growthDays: 90,
    optimalTemp: '15~20°C',
    sowingPeriod: '3월 ~ 4월',
    harvestPeriod: '6월 ~ 7월',
    difficulty: 1,
    pests: ['역병', '감자역병'],
  },
  {
    rank: 5,
    cropId: 5,
    cropName: '당근',
    category: '채소류',
    score: 79,
    soilFitness: 'SUIT',
    soilFitnessPercent: 78,
    priceForecastPercent: 72,
    supplyStabilityPercent: 82,
    supplyStatus: 'BALANCED',
    expectedRevenuePerKg: 2300,
    expectedYield: 6200,
    aiReason: '배수가 양호한 사양토에서 생육이 우수하며, 안정적인 수급 상태를 유지하고 있습니다. 다른 작물과 윤작 시 토양 건강에도 긍정적입니다.',
    growthDays: 100,
    optimalTemp: '15~22°C',
    sowingPeriod: '3월 ~ 4월',
    harvestPeriod: '7월 ~ 8월',
    difficulty: 2,
    pests: ['기생파리', '검은무늬병'],
  },
  {
    rank: 6,
    cropId: 6,
    cropName: '깻잎',
    category: '채소류',
    score: 76,
    soilFitness: 'POSSIBLE',
    soilFitnessPercent: 72,
    priceForecastPercent: 80,
    supplyStabilityPercent: 70,
    supplyStatus: 'EXCESS_CAUTION',
    expectedRevenuePerKg: 8500,
    expectedYield: 1200,
    aiReason: '높은 kg당 단가가 매력적이나, 현재 공급 과잉 주의 상태입니다. 소규모 재배로 직거래 판로를 확보하면 수익성이 좋습니다.',
    growthDays: 60,
    optimalTemp: '20~25°C',
    sowingPeriod: '4월 ~ 6월',
    harvestPeriod: '연중 (시설재배)',
    difficulty: 1,
    pests: ['진딧물', '응애'],
  },
  {
    rank: 7,
    cropId: 7,
    cropName: '양파',
    category: '채소류',
    score: 74,
    soilFitness: 'SUIT',
    soilFitnessPercent: 76,
    priceForecastPercent: 68,
    supplyStabilityPercent: 74,
    supplyStatus: 'SHORT_WARN',
    expectedRevenuePerKg: 1500,
    expectedYield: 9800,
    aiReason: '양평군 내 양파 공급이 심각하게 부족한 상태로, 재배 시 수급 안정에 기여할 수 있습니다. 대량 재배 시 수익도 기대됩니다.',
    growthDays: 180,
    optimalTemp: '15~20°C',
    sowingPeriod: '9월 (파종) / 11월 (정식)',
    harvestPeriod: '이듬해 6월',
    difficulty: 2,
    pests: ['노균병', '잎마름병'],
  },
];

/** 목업 응답 생성 함수 */
export function getMockRecommendResponse(farmId: number, farmName: string): CropRecommendResponse {
  return {
    farmInfo: {
      id: farmId,
      name: farmName,
      address: '경기도 양평군 양서면 부용리 123',
      area: 3300,
      soilPh: 6.2,
      organicMatter: 28.5,
      soilType: '사양토',
    },
    recommendations: MOCK_RECOMMENDATIONS,
    generatedAt: new Date().toISOString(),
  };
}
